# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
    # Primary container image where all steps run
     - image: cimg/node:18.8.0

    steps: 
      - checkout
      - run: 
          name: install dependencies
          command: |
            echo "nothing needs to be installed"
      - run: 
          name: Run test
          command: |
            echo "no tests"
      - run:
          name: Build docker image
          command: |
            docker --version # print the version for logging
            docker build -t simple-node .
            docker tag simple-node 2bit2bit/simple-node:latest
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push 2bit2bit/simple-node:latest

            
workflows:
  build_test:
    jobs:
      - build
      


           