name: Build docker image and push to docker hub

on:
  push:
    branches:
      - 'main'
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      
      
      name: scripts
      run: |
        docker build -t simple-node .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag simple-node YOUR_DOCKER_HUB/simple-node
        docker push 2bit2bit/simple-node
